FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["consumer-app.csproj", "."]
RUN dotnet restore "consumer-app.csproj"
COPY . .
RUN dotnet build "consumer-app.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "consumer-app.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "consumer-app.dll"]
